# Generated by Django 5.2.3 on 2025-06-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sedan', max_length=50)),
                ('cedula', models.IntegerField()),
                ('placa', models.CharField(default='Sedan', max_length=20)),
                ('modelo', models.CharField(default='Sedan', max_length=50)),
                ('color', models.CharField(default='Sedan', max_length=50)),
            ],
        ),
    ]
