# Generated by Django 5.2.3 on 2025-06-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietarioss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='cedula',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
