# Generated by Django 5.2.3 on 2025-06-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietarioss', '0002_alter_propietario_cedula_alter_propietario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='placa',
            field=models.CharField(max_length=20),
        ),
    ]
